### ISSUE TITLE
basic setup fails: error Command "storybook" not found.

### ISSUE THREAD

**Issue by dd-ssc** [storybookjs/react-native#122] opened 2020-10-26 12:50 UTC
**Describe the bug**
Storybook setup fails.

**To Reproduce**
Following [official documentation](https://github.com/storybookjs/react-native#getting-started):

```
$ npx -p @storybook/cli sb init --type react_native
```

+ hit ENTER to select _No_ when asked `install dependencies necessary to run Storybook server?`
+ try to run as instructed by the setup tool output:

```
$  yarn storybook
yarn run v1.22.10
error Command "storybook" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
Storybook should be usable after basic setup.

**Screenshots**
n/a

**Code snippets**
n/a

**System:**

```
$ npx -p @storybook/cli@next sb info

Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  Binaries:
    Node: 14.14.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.111
    Firefox: 81.0.1
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^5.3 => 5.3.21
    @storybook/addon-knobs: ^5.3 => 5.3.21
    @storybook/addon-links: ^5.3 => 5.3.21
    @storybook/addon-ondevice-actions: ^5.3.23 => 5.3.23
    @storybook/addon-ondevice-knobs: ^5.3.23 => 5.3.23
    @storybook/react-native: ^5.3.23 => 5.3.23
```

**Additional context**

React Native project was created hours ago using [offical docs](https://reactnative.dev/docs/environment-setup):

```
$ npx react-native init <project name>
```

**Comment by dd-ssc** [comment] 2020-10-26 13:29
Also tried [manual setup](https://github.com/storybookjs/react-native/blob/master/app/react-native/docs/manual-setup.md), but `yarn add @storybook/react-native` just installs the package and doesn't seem to set up any scripts in the project, either.

**Comment by dd-ssc** [comment] 2020-10-26 13:33
Also tried responding with `Yes` when asked `install dependencies necessary to run Storybook server?` --> Storybook seems to work now.

**Comment by dannyhw** [comment] 2020-11-03 21:34
@dd-ssc the command to run storybook for react native would be `yarn ios` or `yarn android`. The command `yarn storybook` is only added to project if you want storybook server because the `yarn storybook` command starts "react-native-server" which is an optional package. Sorry if this caused confusion but actually this was working as intended since you initially chose to not install react-native-server. 

I'll close this issue since it seems to be resolved but let me know if you feel I should re-open it. Thanks :).

**Closed as completed by dannyhw** 2020-11-03 21:34 UTC
