### ISSUE TITLE
I have infinity loading

### ISSUE THREAD

**Issue by DenisVASI9** [storybookjs/react-native#139] opened 2020-11-22 14:55 UTC
**Describe the bug**
I have infinity loading after start in storybook react-native edition. Without errors or warnings. How does it fix or find?

**To Reproduce**

1. npx -p @storybook/cli sb init --type react_native
2. add export {default} from "./storybook" to index.js
2. npx react-native start
3. npx react-native run-android
4. npm run storybook
5. infinity-loading

**System**
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
  Binaries:
    Node: 12.19.1 - ~/.nvm/versions/node/v12.19.1/bin/node
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.1/bin/npm
  Browsers:
    Chrome: 86.0.4240.193
    Firefox: 83.0
  npmGlobalPackages:
    @storybook/cli: 6.1.1

**Comment by soullivaneuh** [comment] 2020-12-02 00:12
I have a infinite loading too, but on the menu only:

![image](https://user-images.githubusercontent.com/1698357/100811677-72487c80-343b-11eb-93f1-b245018c02cf.png)

I just followed the tutorial steps: https://www.learnstorybook.com/intro-to-storybook/react-native/en/get-started/

**Comment by soullivaneuh** [comment] 2020-12-02 23:17
I just figured out I spoke too fast and didn't read the documentation show on the default content.

However, I also run `npm run android` and opened the expo project on my phone, but I still don't see any change about the menu.

I keep digging, however this is maybe not related with the original issue.

**Comment by dannyhw** [comment] 2020-12-03 19:00
@soullivaneuh hey this issue is actually already a known one and this is a duplicate of an existing issue #55. Please read through that issue and try some of the solutions there and if necessary add your comments on that issue instead. 

I'll close this for now as to not have many duplicates of the same issue, let me know if it needs to be re-opened though :)

**Closed as completed by dannyhw** 2020-12-03 19:00 UTC
