### ISSUE TITLE
storybook for  React Native can't excute resolve of promise

### ISSUE THREAD

**Issue by chundeluoyetian** [storybookjs/react-native#57] opened 2020-06-03 10:19 UTC
If you are reporting a bug or requesting support, start here:
### Bug or support request summary
When your start a story about react native component, you write a promise in the component and the promise's then does't work.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react-native 5.3.18
- @storybook/addons 5.3.18

### Screenshots / Screencast / Code Snippets (Optional)
code of story is as as below
```js
import React from "react";
import { storiesOf } from "@storybook/react-native";
import Article from "./Article";

storiesOf("Article", module)
  .add("mock data", () => (
    <Article
    />
  )
```

code of component is as as below
```js
import React, { Component } from "react";
import { View, Text } from "react-native";
export default class Article extends Component {
  public constructor(props) {
    super(props);
    this.state= {
      content: ''
    };
  }
  componentDidMount() {
    const getContent = new Promise((resolve) => {
      setTimeout(() => {
          resolve('Hello World')
      },3000)
    })
    getContent.then(res => {
      this.setState({content: res})
    }).catch(e => {
      console.log(e)
    });
  }

  render() {
    const { content } = this.state;
    return (
      <View>
        <Text>{content}</Text>
      </View>
    );
  }
}

```
The function of setTimeout has been called,but getContent.then didn't work.I test same scene in  
storybook for React, the then of promise works.Did storybook for  React Native do something for promise so that it can't work?

**Comment by dannyhw** [comment] 2020-08-04 21:39
In my use cases I have no problem executing code with promises so I'm tempted to say that the issue might be something else. If you use the component outside of storybook does it work?

**Comment by Jpoliachik** [comment] 2020-09-25 18:51
I'm seeing this exact same issue on a very barebones app with dependencies: 

```
"dependencies": {
    "@storybook/react-native": "^5.3.21",
    "react": "16.11.0",
    "react-native": "0.62.2"
}
```

Prevents me from using Storybook entirely.

**Comment by dannyhw** [comment] 2020-09-25 20:38
@Jpoliachik are you using promise.finally? Promise.finally is broken for storybook because of corejs transforms being used upstream by core.

**Comment by Jpoliachik** [comment] 2020-09-25 20:41
Not explicitly using `finally`, no. The same promise used in `componentDidMount` in the example above ^ was broken for me.

**Comment by dannyhw** [comment] 2020-09-25 20:46
Ok maybe the issue is related. I'll look into it, thanks for letting us know.

**Comment by intergalacticspacehighway** [comment] 2020-12-03 09:51
@Jpoliachik @dannyhw this is something to do with core-js promise polyfill. We were facing the same issue i.e. Promises never resolved. I commented the es.promise.js from core-js and it started working. 
Also, rn-host-detect.js never imports promise polyfill but due to some reason it's still being imported. Not sure how.

**Comment by dannyhw** [comment] 2020-12-03 10:08
Yes this issue is the same as the promise.finally one, it comes from the storybook client or core package which is polyfilled. It's a direct dependency of react native storybook. It's hard to solve because it requires changes to how to main repo gets built/released. At least that's the impression I got when I investigated last time around.

**Comment by intergalacticspacehighway** [comment] 2020-12-03 12:40
Okay. Thanks for the quick response @dannyhw! 
Just putting it here as a temp fix till a permanent solution is achieved.
We ended up using patch-package - https://www.npmjs.com/package/patch-package. 
- Go to `node_modules/core-js`, comment the `es.promise.js` file in the `modules` directory and run the patch-package command.

**Comment by nickplee** [comment] 2021-06-01 20:26
https://github.com/storybookjs/react-native/issues/159#issuecomment-852422659

**Comment by pierpo** [comment] 2021-07-06 08:40
I just faced the same issue. It seems critical, since it happened to _all_ my colleagues that were using storybook on RN 0.64. Most of them simply removed the library.

It broke in many different ways, and it lead to obscure bugs that are very hard to investigate.

Thanks for the workarounds! But the hardest part is finding this issue 😞 

Is there any plan to solve this?

**Comment by dannyhw** [comment] 2021-07-06 09:57
@pierpo
> Is there any plan to solve this?

There won't be a fix in 5.3 because it's not possible without the 6.0 version of storybook dependencies. The fix is already in the 6.0 alpha that is in progress however the first alpha release has not been done yet. The initial alpha release will be done once the controls PR is completed.

**Comment by pierpo** [comment] 2021-07-06 10:31
> @pierpo
> 
> > Is there any plan to solve this?
> 
> There won't be a fix in 5.3 because it's not possible without the 6.0 version of storybook dependencies. The fix is already in the 6.0 alpha that is in progress however the first alpha release has not been done yet. The initial alpha release will be done once the controls PR is completed.

Amazing @dannyhw! Thank you 😊

**Comment by pierpo** [comment] 2021-07-06 13:43
If someone encounters the same issue, the following changes together solved it:

- upgrade `@storybook/react-native` to `6.0.0-alpha.0`
- in `metro.config.js`, set the `inlineRequires` to `false`

(only upgrading wasn't enough, disabling inline requires was necessary as well)

**Comment by dannyhw** [comment] 2021-07-06 17:58
@pierpo the 6.0.0-alpha is a very old build of the alpha (over a year) I don't recommend using it.

**Comment by pierpo** [comment] 2021-07-07 08:38
Oh! That's the only alpha build I found, I thought it was okay.

![image](https://user-images.githubusercontent.com/6313316/124727827-5b0cc880-df0f-11eb-9bc2-76c9d7c22521.png)

Any other recommendation besides waiting? From our perspective, an unstable storybook build where our promises work is still better than broken promises or no storybook at all 😅

**Comment by dannyhw** [comment] 2021-07-07 11:40
@pierpo there might be some solutions here #20 

You can try making a patch with this change

If you open up
node_modules/@storybook/addons/dist/index.js

and comment out line 11 `//require("core-js/modules/es.promise");`

**Comment by pierpo** [comment] 2021-07-13 14:13
Indeed, it works better. It turns out I still had issues... on iOS 😱  (I thought this was Android specific...)

To sum up:

If someone encounters the same issue, the following changes together solved it.
Using the following versions:

```
    "@storybook/addon-actions": "5.3.21",
    "@storybook/addon-links": "5.3.21",
    "@storybook/addons": "5.3.21",
    "@storybook/react-native": "5.3.25",
```

Then:
- in metro.config.js, I set the `inlineRequires` to `false`
- I used the `patch-package` to remove the `es.promises` import in `node_modules/@storybook/addons/dist/index.js`

```diff
diff --git a/node_modules/@storybook/addons/dist/index.js b/node_modules/@storybook/addons/dist/index.js
index 589d611..36dd045 100644
--- a/node_modules/@storybook/addons/dist/index.js
+++ b/node_modules/@storybook/addons/dist/index.js
@@ -8,7 +8,7 @@ require("core-js/modules/es.object.to-string");
 
 require("core-js/modules/es.object.values");
 
-require("core-js/modules/es.promise");
+// require("core-js/modules/es.promise");
 
 require("core-js/modules/web.dom-collections.for-each");
```

Thank you @dannyhw !

**Comment by dannyhw** [comment] 2021-07-13 15:30
@pierpo glad that you're able to get it working 🙂

**Comment by pierpo** [comment] 2021-07-19 10:26
I don't get it. I still have issues with promises on iOS, despite the fix above.

I even tried the new 6.0 alpha... But I still get the issue.

I just did something that worked, but it's probably not a good idea: I did a patch that deleted the content of all `es.promise.*` files in `core-js`. At least I'm sure that _no one_ will import the polyfill.

Any idea on why this keeps happening?

**Comment by dannyhw** [comment] 2021-07-19 12:05
@pierpo in the new alpha you need to use `resolverMainFields: ['sbmodern', 'main']` in your metro config to get the modern build of storybook packages. Many of the packages have this polyfill and others that cause problems, in the new alpha it's fixed and I've added an example in the example project specifically to verify this bug is fixed.

To test the new alpha check this guide:
https://github.com/storybookjs/react-native/blob/next-6.0/v6README.md

Not sure what alpha version you were using but this is the correct one:
https://github.com/storybookjs/react-native/releases/tag/v6.0.1-alpha.0

It requires some work to migrate to the new version though and I haven't made a migration guide just yet.

**Comment by pierpo** [comment] 2021-07-19 12:07
Amazing. I'll try this out.

Thank you for your commitment to this 😊

**Comment by mdobroggg** [comment] 2021-08-06 19:31
@dannyhw When I use `resolverMainFields: ['sbmodern', 'main'],` in my metro config it breaks node-base imports like http and https

```
error: Error: Unable to resolve module http from /node_modules/axios/lib/adapters/http.js

**Comment by dannyhw** [comment] 2021-08-06 20:06
> @dannyhw When I use `resolverMainFields: ['sbmodern', 'main'],` in my metro config it breaks node-base imports like http and https
> 
> ```
> error: Error: Unable to resolve module http from /node_modules/axios/lib/adapters/http.js

Are you using expo? You can try extending the default main fields, something like
`: ['sbmodern', ...defaults.resolver.resolverMainFields]`

**Comment by Peeeep** [comment] 2022-02-25 10:38
For those struggling with resolverMainFields – the array needs 'react-native' included, too: 

`['sbmodern', 'react-native', 'main']` 
and for expo `['sbmodern', 'react-native', ...defaultConfig.resolver.resolverMainFields]`

See https://github.com/storybookjs/react-native/pull/325 and https://github.com/storybookjs/react-native/commit/8d459bdbce0d13235d4a2b399119fb8bba8e4bae

**Comment by dannyhw** [comment] 2022-02-25 12:41
@Peeeep yes that does seem to be the case for some packages now.

However since this is now resolved in 6.0 beta and also is mostly a duplicate of #20 I think it makes sense to close this issue.

Also for 5.3 you can patch storybook/addons to remove the es promise polyfill that fixes this.

```
diff --git a/node_modules/@storybook/addons/dist/index.js b/node_modules/@storybook/addons/dist/index.js
index 589d611..81bc9e7 100644
--- a/node_modules/@storybook/addons/dist/index.js
+++ b/node_modules/@storybook/addons/dist/index.js
@@ -8,8 +8,6 @@ require("core-js/modules/es.object.to-string");
 
 require("core-js/modules/es.object.values");
 
-require("core-js/modules/es.promise");
-
 require("core-js/modules/web.dom-collections.for-each");
 
 Object.defineProperty(exports, "__esModule", {
 ```

**Closed as completed by dannyhw** 2022-02-25 12:41 UTC
Labels: needs reproduction

**Comment by deiden26** [comment] 2023-01-06 03:17
> Also for 5.3 you can patch storybook/addons to remove the es promise polyfill that fixes this.

Hi @dannyhw. I've tried this patch

```bash
> cat patches/@storybook+addons+5.3.21.patch
diff --git a/node_modules/@storybook/addons/dist/index.js b/node_modules/@storybook/addons/dist/index.js
index 589d611..8ae3a82 100644
--- a/node_modules/@storybook/addons/dist/index.js
+++ b/node_modules/@storybook/addons/dist/index.js
@@ -8,8 +8,6 @@ require("core-js/modules/es.object.to-string");

 require("core-js/modules/es.object.values");

-require("core-js/modules/es.promise");
-
 require("core-js/modules/web.dom-collections.for-each");

 Object.defineProperty(exports, "__esModule", {
```

but I still end up with errors:

```
 ERROR  [TypeError: new Promise(function (resolve) {
      remoteResolve = resolve;
    }).finally is not a function. (In 'new Promise(function (resolve) {
      remoteResolve = resolve;
    }).finally(function () {
      clearTimeout(autoResolveTimeout);
    })', 'new Promise(function (resolve) {
      remoteResolve = resolve;
    }).finally' is undefined)]
```

I've tried restarting the Metro server without any caching to no avail. Do you have any suggestions?

**Comment by dannyhw** [comment] 2023-01-06 12:02
@deiden26 try searching your node_modules for this `require("core-js/modules/es.promise");` and remove it in every instance.
