### ISSUE TITLE
styled-components ThemeProvider not working inside stories

### ISSUE THREAD

**Issue by MigueloAtla** [storybookjs/react-native#472] opened 2023-05-02 18:42 UTC
**Describe the bug**
I'm using styled-components in my react-native application, and I want to develop my components using storybook.
I have configured the decorators like in this [tutorial](https://storybook.js.org/recipes/styled-components), so I have this decorator:
```js
// .storybook/preview.js
import { withThemeFromJSXProvider } from "@storybook/addon-styling"
import { ThemeProvider } from "styled-components"
import { theme } from "../src/styles/theme"

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
}

export const decorators = [
  withThemeFromJSXProvider({
    themes: {
      light: theme,
      dark: theme,
    },
    defaultTheme: "light",
    Provider: ThemeProvider,
  }),
]
```
I also tried to configure like this:
```js
// .storybook/preview.js
import { withThemeFromJSXProvider } from "@storybook/addon-styling"
import { ThemeProvider as StyledComponentsThemeProvider } from "styled-components"
import { theme } from "../src/styles/theme"

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
}
export const decorators = [
  Story => {
    return (
      <ThemeProvider theme={theme}>
        <Story />
      </ThemeProvider>
    );
  },
];
```
The problem is that theme is not propagated to the styled component when it runs on storybook.
ThemeContext is working well:
```js
const themeContext = useContext(ThemeContext)
console.log("Current theme: ", themeContext) // displays my theme correctly
```
but:
```js
const ButtonTextStyled = styled.Text`
  font-size: 60px;
  ${(props) => console.log(props.theme)} // theme is an empty object
`
```
In app, all the styles and theme are working well, and same configuration on a react project works well with storybook. Only facing this issue on storybook/react-native.

**To Reproduce**
1. repository: https://github.com/MigueloAtla/storybook-boilerplate
2. yarn, to install dependencies
3. yarn storybook:web
4. In dev tools, you can see the logs

**Expected behavior**
Styled component should receive the theme from the theme provider:
```js
const ButtonTextStyled = styled.Text`
  font-size: 60px;
  ${(props) => console.log(props.theme)} // it should have the theme properties
`
```

**Comment by dannyhw** [comment] 2023-06-25 22:21
thanks for providing this repro and sorry I've been very busy recently I will try to look into it soon.

**Comment by dannyhw** [comment] 2023-10-22 20:44
this should be fixed in the latest version 6.5.6. If you find its still not working then please let me know and I will reopen.

**Closed as completed by dannyhw** 2023-10-22 20:44 UTC

**Comment by MrRefactoring** [comment] 2025-05-31 13:58
I just migrated to Storybook v9 and got exactly the same behavior

**Comment by dannyhw** [comment] 2025-05-31 20:38
That shouldn't be the case if you are wrapping stories with your provider. There is no longer a reason i can think of that this would happen. If you share a reproduction i can take a look though.

**Comment by MrRefactoring** [comment] 2025-06-08 14:03
Hi Daniel! Thank you for your response and for agreeing to look at the issue. I've created a small example where the theme isn't working. I'm not very experienced in creating custom Storybook components, but I'd be really grateful if you could take a look.

Here's my repository with the example:  
https://github.com/MrRefactoring/sb-theme/blob/master/stories/test.stories.tsx#L7

Originally, I encountered this problem while migrating from version 8 to 9 of Storybook for this repository:  
https://github.com/UX-and-I/storybook-design-token/blob/master/addon/src/components/TokenTable.tsx#L73  
where it used to work before.

**Comment by dannyhw** [comment] 2025-06-08 14:10
isn't it because you are using `import { styled } from "@storybook/theming";` instead of from styled-components?

**Comment by dannyhw** [comment] 2025-06-08 14:13
wait it seems like you've linked a web storybook which makes this unrelated to this repository, no?

**Comment by MrRefactoring** [comment] 2025-06-08 14:30
I saw this issue that looked very similar to my problem. I understand the repositories are different, but I thought it made sense to reference it. Are you suggesting I move my question to the main Storybook repository?

**Comment by dannyhw** [comment] 2025-06-08 15:31
Yes the implementation is very different in react native, the ui and theming library is completely rewritten. I wouldn't have much insight on this issue unfortunately.

**Comment by MrRefactoring** [comment] 2025-06-08 19:11
Alright, I’ll spend some more time looking into the issue, and if needed, I’ll create an issue in the main repository. In any case, I’m extremely grateful that you didn’t stay indifferent and responded to my request for help with this problem.
