### ISSUE TITLE
sb-rn-get-stories only support main.js, does not support tsx file format

### ISSUE THREAD

**Issue by xiongemi** [storybookjs/react-native#324] opened 2022-02-06 21:57 UTC
**Describe the bug**

https://github.com/storybookjs/react-native/blob/06d36c6f14b193b8f1c52a40a56acd613c3a96c5/app/react-native/scripts/loader.js#L41

**To Reproduce**
1. create a react native with typescript
2. run the sb-rn-get-stories
3. it only support js file

It throw this error:
```
Error: Cannot find module '/Users/emilyxiong/Code/tmp/nx-react-native-storybook2/apps/app/src/main.js'
Require stack:
- /Users/emilyxiong/Code/tmp/nx-react-native-storybook2/node_modules/@storybook/react-native/scripts/loader.js
- /Users/emilyxiong/Code/tmp/nx-react-native-storybook2/node_modules/@storybook/react-native/scripts/get-stories.js
- /Users/emilyxiong/Code/tmp/nx-react-native-storybook2/node_modules/@storybook/react-native/bin/get-stories.js
```

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

**Additional context**

**Comment by dannyhw** [comment] 2022-02-07 20:18
I'm closing this as a duplicate of #295. Please continue discussion there if necessary.

**Closed as completed by dannyhw** 2022-02-07 20:18 UTC
