### ISSUE TITLE
[6.0] Improve navigator design to more closely match web

### ISSUE THREAD

**Issue by codybrouwers** [storybookjs/react-native#338] opened 2022-03-20 18:43 UTC
### **Is your feature request related to a problem? Please describe.**

It would be great if the navigator grouped stories separated by `/` like in the web navigator. I saw @a7med-mahmoud's great work in #326 which brings us a lot closer and it would be great if we tried to match web as closely as possible.

### **Describe the solution you'd like**

Ideally the navigator should match web as closely as possible, but I threw together the below proposed layout that is just requires a few changes to the `StoryListView` component. This works when I use a story title like: `atoms/Checkbox` and exporting a story titled `Default`. Happy to create a PR if it looks good!

I also saw this [note](https://github.com/storybookjs/react-native/blob/next-6.0/MIGRATION.md#simplified-hierarchy-separators) in the migration doc, is it relevant for 6.0?

### **Are you able to assist bring the feature to reality?**
For sure!

Thanks @dannyhw for all of your work on React Native Storybook, I really appreciate it! 😊 I recently watched your [interview](https://youtu.be/kPLrhkvdnD8) with Jamon Holmgren a few weeks ago which helped provide a bunch of backstory to the project, thanks for that!

|Web|Current|Proposed|
|:-:|:-:|:-:|
<img width="200" alt="image" src="https://user-images.githubusercontent.com/11965195/159177039-1bea3202-9105-4e70-8be7-02988bd84c33.png"> |  <img width="200" alt="image" src="https://user-images.githubusercontent.com/11965195/159177241-b120914b-5d33-4357-bd17-17711645df09.png"> | <img width="270" alt="image" src="https://user-images.githubusercontent.com/11965195/159177166-4e175748-a978-4a54-97d6-0ac82dd3ffb9.png">

**Comment by dannyhw** [comment] 2022-03-20 19:49
@CodyBrouwers hey! thanks for the kind words :)

Yeah actually this has been planned for a long time and I actually almost included something like this but I just never decided on the right approach.

Currently the way the stories are set up in the sidebar is a bit over complicated so I've been wanting to re-do it.

Right now there is a bit of a rewrite already undergoing for the 6.4 storybook support so I'm waiting for that to be complete before I work on anything else. However I think any conflicts would be minimal since the work ongoing is around the integration with core storybook apis.

However this is definitely one of the main features that I'd like to add either before or after 6.0 stable.

If you want to have a go at implementing then please feel free to open a PR and I'll be happy to help with it 🙏

**Comment by dannyhw** [comment] 2022-03-20 19:57
There isn't currently anything to parse the story names for categories etc so that would need to be worked on.

The best thing would be to copy the web implementation probably, however it's quite different now with the rework done to the search etc.

The feature itself should be easy but the problem is making it performant and readable since the existing code is pretty unoptimized and hard to read.

**Comment by codybrouwers** [comment] 2022-03-22 02:59
Glad to hear this is on your radar! 😄

I found [this folder](https://github.com/storybookjs/storybook/tree/next/lib/ui/src/components/sidebar) in the web repo, is it the best place to find the web's implementation of the navigator?

If you don't think there will be too many conflicts with upcoming work then I will definitely give it a go!

**Comment by dannyhw** [comment] 2022-03-23 13:16
@CodyBrouwers yeah that looks like the right place, seems to be a hierarchy a bit like Sidebar-> explorer -> ref -> tree

Its a bit more complex in their version of it since they have a different UI for the search results, I guess we could do the same though.

Yeah if your changes are mostly in [storylistview](https://github.com/storybookjs/react-native/blob/next-6.0/app/react-native/src/preview/components/StoryListView/StoryListView.tsx) then it should be mostly free from conflicts. 

Please let me know if I can help at all :)

**Comment by ckollars** [comment] 2022-04-01 14:10
I came here to see if I could be of any assistance since this would be great to have on device.

@CodyBrouwers Let me know if you need a second pair of 👀 on anything.

**Comment by leojclarke** [comment] 2022-07-15 10:21
Ah, I've been trying to find the syntax to group my components by category, but is it right, this is only possible for Web stories or am I missing something?

Currently I write my stories like this:

```
// Button.stories.tsx
storiesOf('Button', module)
  .addDecorator(withKnobs)
  .addDecorator((getStory) => <CenterView>{getStory()}</CenterView>)

  .add('signup button with facebook icon and text', () => (
    <Button
      onPress={() => alert('You pressed the sign up with facebook button')}
      icon={'facebook'}
      text={'Sign up with Facebook'}
    />
  ));
```

Which just results in a huge long list in the sidebar (I like using the web interface and have the full preview open on the device).

So currently there is no way to write something like this:

```
// Checkbox.stories.js
import { Checkbox } from './Checkbox';
 
export default {
 title: 'Design System/Atoms/Checkbox',
 component: Checkbox,
};
```
It would be awesome to bring react-native closer to the web (also, the react-native docs are very hidden on the storybookjs website... 😔

Thanks @dannyhw for all your work! I'm gonna go checkout your interview with Jamon!

**Comment by kyle-ssg** [comment] 2022-10-08 19:38
Have been searching for issues and this was the closest I'd found, I thought it would have been possible to control react-native storybook via a web UI, I feel like that would make things way easier. I did something similar where a performance monitor would send commands to react-native via WebSockets https://github.com/Flagsmith/react-native-performance-monitor.

I just wonder if it'd be possible to reuse the web storybook UI and clicking stories would just send messages to the app to tell it to open the story.

**Comment by dannyhw** [comment] 2022-10-09 10:41
@kyle-ssg thats basically what storybook/react-native-server is in the stable version (5.3).

I haven't been able to find a way to make it work yet in the v6 beta. Though I intend to support the same web-socket updates even if the server package isn't updated.

**Comment by kyle-ssg** [comment] 2022-10-18 09:39
Oh right, in that case, brilliant - can't wait to see this working!

**Comment by dannyhw** [comment] 2023-03-01 10:59
The pr for this was already merged so closing this as resolved

**Closed as completed by dannyhw** 2023-03-01 10:59 UTC
Labels: 6.5
